version: "2.0"

services:
  render-node:
    build:
      context: ./render
      args:
         NDVIZHOST : $HOSTNAME
         NDVIZPORT : 8001
    ports:
        - 8080
    environment:
        - NDVIZHOST:$HOSTNAME:8001

