version: "2.0"
services:
 renderservice:
    build:
      context: ./render
    links:
      - mongo
 mongo:
    image: mongo:3.4.2
    ports:
        - "27017"
    restart: always
    security_opt:
      - seccomp:unconfined
 render-python:
   build:
      context: ./render
   links:
     - renderservice
   volumes:
     - ./test-reports:/usr/local/render-python/test-reports
     - ./htmlcov:/usr/local/render-python/htmlcov
