version: "3.0"
services:
 log:
  build: ./loggly
  ports:
     - "514:514"
     - "514:514/udp"
  env_file:
     - loggly.env
 render:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
        - log:log
    ports:
        - "80:80"
        - "8080:80" 
 node1:
    build: ./render
    ports:
        - "8091:8080"
    volumes:
        - /nas:/nas:ro
        - /nas2:/nas2:ro
        - /nas3:/nas3:ro
        - /nas4:/nas4:ro
    links:
        - mongo
        - log:log
    logging:
        driver: "syslog"
        options:
           syslog-address: "udp://localhost:514"
           tag: "rendernode1"
 node2:
    build: ./render
    ports:
        - "8092:8080"
    volumes:
        - /nas:/nas:ro
        - /nas2:/nas2:ro
        - /nas3:/nas3:ro
        - /nas4:/nas4:ro
    links:
        - mongo
        - log:log
    logging:
        driver: "syslog"
        options:
           syslog-address: "udp://localhost:514"
           tag: "rendernode2"    
 node3:
    build: ./render
    ports:
        - "8093:8080"
    volumes:
        - /nas:/nas:ro
        - /nas2:/nas2:ro
        - /nas3:/nas3:ro
        - /nas4:/nas4:ro
    links:
        - mongo
        - log:log
    logging:
        driver: "syslog"
        options:
           syslog-address: "udp://localhost:514"
           tag: "rendernode3"
 mongo:
    image: mongo:3.4.2
    ports:
        - "27017:27017"
    volumes:
        - /mnt/SSD/mongodb:/data/db
    restart: always
    links:
       - log:log
    security_opt:
      - seccomp:unconfined
    logging:
       driver: "syslog"
       options:
           syslog-address: "udp://localhost:514"
           tag: "mongo"
 ndviz:
   image: ndvizv2:latest
   ports:
       - "8889:8000"
       - "8001:8000"
   links:
       - render
       - log:log     
   logging:   
       driver: "syslog"
       options:
           syslog-address: "udp://localhost:514"
           tag: "ndviz"
