version: "2.0"
services:
 log:
  build: ./loggly
  ports:
     - "514:514"
     - "514:514/udp"
  environment:
     - TOKEN=$LOGGLYTOKEN
     - TAG=RenderDeployStack
 render:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
        - log:log
        - ndviz:ndviz
    ports:
        - "80:80"
        - "8080:80"
        - "8082:80" 
        - "8081:80"
 node1:
    extends:
       file: 'common.yml'
       service: render-node
    links:
       - mongo
       - log:log
    logging:
       options:
          tag: render-node1
 node2:
    extends:
       file: 'common.yml'
       service: render-node
    links:
       - mongo
       - log:log
    logging:
       options:
          tag: render-node2
 node3:
    extends:
       file: 'common.yml'
       service: render-node
    links:
       - mongo
       - log:log
    logging:
       options:
          tag: render-node3
 mongo:
    image: mongo:3.4.2
    ports:
        - "27017:27017"
    volumes:
        - /mnt/SSD/mongodb:/data/db
    restart: always
    links:
       - log:log
    security_opt:
      - seccomp:unconfined
    logging:
       driver: "syslog"
       options:
           syslog-address: "udp://localhost:514"
           tag: "mongo"
 ndviz:
   image: fcollman/ndviz:latest
   ports:
       - "8889:8000"
       - "8001:8000"
   links:
       - log:log     
   logging:   
       driver: "syslog"
       options:
           syslog-address: "udp://localhost:514"
           tag: "ndviz"
