version: "2.0"
services:
 render:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - ndviz:ndviz
    ports:
        - "80:80"
        - "8080:80"
        - "8082:80" 
        - "8081:80"
 node1:
    extends:
       file: 'common.yml'
       service: render-node
    links:
       - mongo
 node2:
    extends:
       file: 'common.yml'
       service: render-node
    links:
       - mongo
 mongo:
    image: mongo:3.4.2
    ports:
        - "27017"
    restart: always
    security_opt:
      - seccomp:unconfined
 ndviz:
   image: fcollman/ndviz:latest
   ports:
       - "8001:8000"
 redis:
   image: redis
   ports:
       - "6379"
 notebook:
   image: fcollman/render-python-apps
   ports:
       - "8889:8888"
   links:
       - render
   volumes:
       - "../render-python-apps/notebooks:/usr/local/render-python-apps/notebook"