version: "2.0"
services:
 renderservice:
    build:
      context: ./render
    ports:
      - "8080:8080"
    links:
      - mongo
 mongo:
    image: mongo:3.4.2
    ports:
        - "27017"
    security_opt:
      - seccomp:unconfined
 render-modules:
   image: fcollman/render-modules
   links:
     - renderservice
   volumes:
     - ./test-reports:/shared/render-modules/test-reports
     - ./htmlcov:/shared/render-modules/htmlcov
