version: "2.0"
services:
 renderservice:
    image: fcollman/render-ws
    ports:
      - "127.0.0.1:9000:8080"
    links:
      - mongo
    volumes:
      - /allen:/allen
      - ./example_1:/tmp/example_1:ro
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
 mongo:
    image: mongo:3.4.2
    expose:
      - "27017"
    security_opt:
      - seccomp:unconfined
