version: "2.0"
services:
 renderservice:
    build:
      context: ./render
    ports:
      - "8080"
    links:
      - mongo
    volumes:
      - /allen:/allen
      - ./example_1:/tmp/example_1:ro
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
 mongo:
    image: mongo:3.4.2
    expose:
      - "27017"
    security_opt:
      - seccomp:unconfined
 render-modules:
   image: fcollman/render-modules
   links:
      - renderservice
   volumes:
      - ./test-reports:/shared/render-modules/test-reports
      - ./htmlcov:/shared/render-modules/htmlcov
      - /allen:/allen
      - ./example_1:/tmp/example_1:ro
   environment:
      - RENDER_EXAMPLE_DATA=/tmp
      - RENDER_CLIENT_SCRIPTS=/shared/render/render-ws-java-client/src/main/scripts
